# Generated by Django 5.1.2 on 2024-10-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storemodels', '0002_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('sneakers', 'Кроссовки'), ('Rubber boots', 'Резиновые сапоги'), ('deck shoes', 'Топсайдеры')], default='Кроссовки', max_length=50, verbose_name='Тип товара'),
        ),
    ]
